/**
 * Exporters.
 *
 * A level that only runs inside this website is a demo. A level that drops into
 * an engine a real developer already uses is a tool. Every generated level is
 * therefore emitted in three forms: the native format, a Godot 4 scene, and a
 * Phaser 3 tilemap-style object layer.
 */

import { Level, MATERIAL_SPECS, WORLD_H, WORLD_W, toWorld } from "./level";

export function toJSON(level: Level): string {
  return JSON.stringify(level, null, 2);
}

/**
 * Godot 4 `.tscn`. Static bodies with rectangle shapes, grouped by material so
 * a `_on_body_entered` handler can branch on the group name.
 */
export function toGodot(level: Level): string {
  const rects = level.entities.map((e) => ({ e, r: toWorld(e.box) }));
  // 1 (root) + 2 nodes per entity (body + shape) + player + goal.
  const loadSteps = rects.length * 2 + 4;

  const head = `[gd_scene load_steps=${loadSteps} format=3]

; Generated by Visoto - https://github.com/mehul1three/visoto
; Source scene: ${JSON.stringify(level.title)}
; World is ${WORLD_W} x ${WORLD_H} px, origin top-left.

[node name="${sanitizeNode(level.title)}" type="Node2D"]
`;

  const bodies = rects
    .map(({ e, r }, i) => {
      const cx = r.x + r.w / 2;
      const cy = r.y + r.h / 2;
      const group = e.material;
      return `
[sub_resource type="RectangleShape2D" id="Shape_${i}"]
size = Vector2(${r.w.toFixed(1)}, ${r.h.toFixed(1)})

[node name="${sanitizeNode(e.label)}_${i}" type="StaticBody2D" parent="."]
position = Vector2(${cx.toFixed(1)}, ${cy.toFixed(1)})
collision_layer = ${MATERIAL_SPECS[e.material].solid ? 1 : 2}
metadata/label = "${escapeStr(e.label)}"
metadata/material = "${group}"
metadata/reason = "${escapeStr(e.reason)}"

[node name="Shape" type="CollisionShape2D" parent="${sanitizeNode(e.label)}_${i}"]
shape = SubResource("Shape_${i}")
`;
    })
    .join("");

  const markers = `
[node name="Spawn" type="Marker2D" parent="."]
position = Vector2(${(level.spawn.x * WORLD_W).toFixed(1)}, ${(level.spawn.y * WORLD_H).toFixed(1)})

[node name="Goal" type="Marker2D" parent="."]
position = Vector2(${(level.goal.x * WORLD_W).toFixed(1)}, ${(level.goal.y * WORLD_H).toFixed(1)})
`;

  return head + bodies + markers;
}

/**
 * Phaser 3 object layer. Drops straight into `this.make.tilemap({ key })` style
 * loading, or can be iterated directly to build static bodies.
 */
export function toPhaser(level: Level): string {
  const objects = level.entities.map((e, i) => {
    const r = toWorld(e.box);
    return {
      id: i + 1,
      name: e.label,
      type: e.material,
      x: Math.round(r.x),
      y: Math.round(r.y),
      width: Math.round(r.w),
      height: Math.round(r.h),
      visible: true,
      rotation: 0,
      properties: [
        { name: "material", type: "string", value: e.material },
        { name: "reason", type: "string", value: e.reason },
        { name: "solid", type: "bool", value: MATERIAL_SPECS[e.material].solid },
        { name: "synthetic", type: "bool", value: !!e.synthetic },
      ],
    };
  });

  return JSON.stringify(
    {
      compressionlevel: -1,
      width: WORLD_W,
      height: WORLD_H,
      infinite: false,
      orientation: "orthogonal",
      renderorder: "right-down",
      tiledversion: "1.10.2",
      type: "map",
      version: "1.10",
      tilewidth: 1,
      tileheight: 1,
      properties: [
        { name: "title", type: "string", value: level.title },
        { name: "spawnX", type: "int", value: Math.round(level.spawn.x * WORLD_W) },
        { name: "spawnY", type: "int", value: Math.round(level.spawn.y * WORLD_H) },
        { name: "goalX", type: "int", value: Math.round(level.goal.x * WORLD_W) },
        { name: "goalY", type: "int", value: Math.round(level.goal.y * WORLD_H) },
      ],
      layers: [
        {
          draworder: "topdown",
          id: 1,
          name: "objects",
          opacity: 1,
          type: "objectgroup",
          visible: true,
          x: 0,
          y: 0,
          objects,
        },
      ],
    },
    null,
    2,
  );
}

function sanitizeNode(s: string): string {
  return (
    s
      .replace(/[^a-zA-Z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 40) || "Node"
  );
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export const EXPORTS = {
  json: { label: "Visoto JSON", ext: "json", mime: "application/json", fn: toJSON },
  godot: { label: "Godot 4 scene", ext: "tscn", mime: "text/plain", fn: toGodot },
  phaser: { label: "Phaser / Tiled", ext: "json", mime: "application/json", fn: toPhaser },
} as const;

export type ExportKind = keyof typeof EXPORTS;
